### ISSUE TITLE
TODO list:

### ISSUE THREAD

**Issue by yyfastow** [yyfastow/ChatBox#1]
### Posts
- [x]  Add comments on posts 
  - [x] make comments like facebook that you could comment on comments 
    - [x] make ajax work for comment to show a new box of the post.
    - [ ] BUG: fix template to only show last 5 comments and have a link that will reveal other comments
        - [ ] SECONDARY: have the link show the next 10 comments than if pressed again show the next 10 until all gone
    - [x] only show comments not replies unless press link
    - [x] only allow user to post comment if it sends a text or photo
  - [x] create comments under post
- [x] Add like buttons on posts and comments
    - [x] hover over like button and it reveals the likes
- [ ] SECONDARY: Add ability to add videos
- [ ] SECONDARY:  add markdown to add code
- [x]  share posts
- [x] send individual messages
  - [ ] SECONDARY send messages to a few selected people.
- [x] show if post is private,public or friends

### Loading Pages/URLS
- [x] make urls that are connected to ajax request to return back to main page or show a 404 when typee in url instead of pressing button

### Search bars
- [x] add search bar to search posts.
- [x] make search bar to search all posts form person.

### Signing up
- [x] redirect user to finding friends page of he has no friends and on friends page
- [x] don't let users with no friends or admin post things as friends

### Profile
- [x] add ability to count amount of friends
- [x] show profile info
- [x] able to update info
- [x] add description to profile model

### Friends
- [ ] SECONDARY:  make groups 
- [ ]SECONDARY: tag people in photos and let them see it
- [ ] tell if friend is you
- [ ] SECONDARY: a better method in finding friends like showing friends of friends
- [ ] BUG: fix link to soporific friend page

### Messages
- [x] use chat.models.FriendMessage to allow user to send messages to soporific user
- [x] all user to respond to a message
- [x] show links to private messages, than show friend_requests and than messages from staff (could have staff messages on one side and requests on other side).
- [x] give number of recient messages instead of all.
- [ ] SECONDARY: make the message form come when press on button on any page instead of going to another page
- [x] respond to message in form under the message (button show the form)
- [x] sort common message by user's   (MAYBE)

### Admin
- [x] fix urls to work for superuser
- [x]  admin can't post to friends and only me
- [x] admin can't make friends only sees a list of friends
- [x] fix tab to work for admin
- [x] make it the no one could take the name "ChatBox staff" as a username or firstname or lastname
- [x] allow admin to respond to messages from user
